(function(){
'use strict';
var $=function(s,r){return (r||document).querySelector(s)},$$=function(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))};
var state={site:null,catalog:null,password:null,current:null,files:new Map(),original:null,monaco:null,editor:null,activeFile:null,done:{},hint:0};
var els={classGrid:$('#classGrid'),classSearch:$('#classSearch'),tagFilter:$('#tagFilter'),levelFilter:$('#levelFilter'),classEmpty:$('#classEmpty'),blogGrid:$('#blogGrid'),blogSearch:$('#blogSearch'),blogEmpty:$('#blogEmpty'),wsTitle:$('#wsTitle'),wsDescription:$('#wsDescription'),fileList:$('#fileList'),fileCount:$('#fileCount'),activeFile:$('#activeFile'),monaco:$('#monaco'),fallback:$('#fallback'),preview:$('#preview'),saveState:$('#saveState'),tasks:$('#tasks'),hints:$('#hints'),original:$('#downloadOriginal'),edited:$('#downloadEdited'),theme:$('#theme'),lock:$('#lock'),password:$('#password'),unlock:$('#unlockForm'),error:$('#error'),portfolioHeader:$('#portfolioHeader'),portfolioFooter:$('#portfolioFooter'),footerText:$('#footerText'),footerMessage:$('#footerMessage')};
function toast(m){var t=document.createElement('div');t.className='toast';t.textContent=m;document.body.appendChild(t);requestAnimationFrame(function(){t.classList.add('show')});setTimeout(function(){t.remove()},1900)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]})}
function safeGet(k){try{return localStorage.getItem(k)}catch(e){return null}}function safeSet(k,v){try{localStorage.setItem(k,v)}catch(e){}}
function view(name){$$('.view').forEach(function(v){v.classList.toggle('active',v.dataset.view===name)});$$('.topnav a').forEach(function(a){a.classList.toggle('active',a.dataset.route===name)});window.scrollTo({top:0,behavior:'smooth'})}
function route(){var h=location.hash.slice(1),parts=h.split('/');if(parts[0]==='class'&&parts[1]){if(state.catalog)openClass(parts[1]);else requireUnlock();return}if(parts[0]==='blog'&&parts[1]){if(state.catalog)openBlog(parts[1]);else requireUnlock();return}view(parts[0]||'home')}
window.addEventListener('hashchange',route);
$$('[data-route]').forEach(function(a){a.addEventListener('click',function(e){var v=a.getAttribute('data-route');if(v!=='home')e.preventDefault();location.hash=v})});
$('#openLab').onclick=function(){location.hash='classes'};$('#backBlogs').onclick=function(){location.hash='blogs'};
$('#theme').onclick=function(){var light=document.body.classList.toggle('light');safeSet('oml-theme',light?'light':'dark')};if(safeGet('oml-theme')==='light')document.body.classList.add('light');

async function siteInfo(){try{state.site=await fetch('./data/site.json',{cache:'no-store'}).then(function(r){return r.json()});var draft=safeGet('oml-editor-draft');if(draft)try{state.site=Object.assign({},state.site,JSON.parse(draft))}catch(e){}var b=state.site.brand||{},f=state.site.footer||{};document.title=b.name||'Obaidul Mentor Lab';if(b.portfolioUrl){els.portfolioHeader.href=b.portfolioUrl;els.portfolioFooter.href=b.portfolioUrl}else{els.portfolioHeader.hidden=true;els.portfolioFooter.hidden=true}els.footerText.textContent=f.text||b.name||'Obaidul Mentor Lab';els.footerMessage.textContent=f.message||''}catch(e){}}
function b64(s){var bin=atob(s),u=new Uint8Array(bin.length);for(var i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return u}
async function derive(password,salt,iterations){var base=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:salt,iterations:iterations,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['decrypt'])}
async function decryptEnv(env,password){var key=await derive(password,b64(env.salt),env.iterations),data=b64(env.data),tag=b64(env.tag),joined=new Uint8Array(data.length+tag.length);joined.set(data);joined.set(tag,data.length);return new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:b64(env.iv),additionalData:new TextEncoder().encode(env.aad||'')},key,joined))}
async function ensureZip(){if(window.JSZip)return true;var urls=['https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js','https://unpkg.com/jszip@3.10.1/dist/jszip.min.js'];for(var i=0;i<urls.length;i++){try{await new Promise(function(resolve,reject){var s=document.createElement('script');s.src=urls[i];s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});if(window.JSZip)return true}catch(e){}}return false}
async function unlock(password){try{var env=await fetch('./data/catalog.enc.json',{cache:'no-store'}).then(function(r){return r.json()}),plain=await decryptEnv(env,password);state.catalog=JSON.parse(new TextDecoder().decode(plain));state.password=password;safeSet('oml-session',password);els.lock.hidden=false;renderCatalog();route();return true}catch(e){return false}}
function requireUnlock(){view('login')}
els.unlock.addEventListener('submit',async function(e){e.preventDefault();els.error.textContent='';var ok=await unlock(els.password.value);if(!ok){els.error.textContent='Incorrect password or unavailable class catalog.';return}els.password.value='';toast('Library unlocked')});
els.lock.onclick=function(){state.catalog=null;state.password=null;state.current=null;safeSet('oml-session','');els.lock.hidden=true;location.hash='home';toast('Library locked')};

function card(item,type){var tags=(item.tags||[]).slice(0,5).map(function(t){return '<span class="badge">'+esc(t)+'</span>'}).join('');var href=type==='class'?'#class/'+encodeURIComponent(item.id):'#blog/'+encodeURIComponent(item.id);return '<article class="card"><div><div class="badges">'+(tags||'<span class="badge">'+type+'</span>')+'</div><h3>'+esc(item.title)+'</h3><p>'+esc(item.description||item.summary||'')+'</p></div><div class="meta"><span>'+esc(item.level||'All levels')+(item.duration?' · '+esc(item.duration):'')+'</span><a class="tiny" href="'+href+'">'+(type==='class'?'Open class →':'Read article →')+'</a></div></article>'}
function populateFilters(){var cs=state.catalog.classes||[],tags=[],levels=[];cs.forEach(function(x){(x.tags||[]).forEach(function(t){if(tags.indexOf(t)<0)tags.push(t)});if(x.level&&levels.indexOf(x.level)<0)levels.push(x.level)});tags.sort();levels.sort();els.tagFilter.innerHTML='<option value="all">All tags</option>'+tags.map(function(t){return '<option>'+esc(t)+'</option>'}).join('');els.levelFilter.innerHTML='<option value="all">All levels</option>'+levels.map(function(t){return '<option>'+esc(t)+'</option>'}).join('')}
function renderClasses(){var q=(els.classSearch.value||'').toLowerCase(),tag=els.tagFilter.value,level=els.levelFilter.value,arr=(state.catalog.classes||[]).filter(function(x){var text=(x.title+' '+x.description+' '+(x.tags||[]).join(' ')).toLowerCase();return text.indexOf(q)>=0&&(tag==='all'||(x.tags||[]).indexOf(tag)>=0)&&(level==='all'||x.level===level)});els.classGrid.innerHTML=arr.map(function(x){return card(x,'class')}).join('');els.classEmpty.hidden=arr.length>0}
function renderBlogs(){var q=(els.blogSearch.value||'').toLowerCase(),arr=(state.catalog.blogs||[]).filter(function(x){return (x.title+' '+x.description+' '+(x.tags||[]).join(' ')).toLowerCase().indexOf(q)>=0});els.blogGrid.innerHTML=arr.map(function(x){return card(x,'blog')}).join('');els.blogEmpty.hidden=arr.length>0}
function renderCatalog(){populateFilters();renderClasses();renderBlogs()}
els.classSearch.oninput=renderClasses;els.tagFilter.onchange=renderClasses;els.levelFilter.onchange=renderClasses;els.blogSearch.oninput=renderBlogs;

function normalizePath(p){p=p.replace(/\\/g,'/').replace(/^\.\//,'');var out=[];p.split('/').forEach(function(part){if(!part||part==='.'){return}if(part==='..')out.pop();else out.push(part)});return out.join('/')}
function textFile(n){return /\.(html?|css|js|json|md|txt|svg)$/i.test(n)}function fileIcon(n){return /\.html?$/i.test(n)?'HTML':/\.css$/i.test(n)?'CSS':/\.js$/i.test(n)?'JS':/\.(png|jpe?g|gif|webp|svg)$/i.test(n)?'IMG':'FILE'}
function saveKey(name){return 'oml-edit-'+state.current.meta.id+'-'+name}function getText(name){var v=safeGet(saveKey(name));if(v!==null)return v;var b=state.files.get(name);return b?new TextDecoder().decode(b):''}function setText(name,v){safeSet(saveKey(name),v);state.files.set(name,new TextEncoder().encode(v))}
function lang(n){return /\.html?$/i.test(n)?'html':/\.css$/i.test(n)?'css':/\.json$/i.test(n)?'json':'javascript'}
async function setupEditor(){try{var monaco=window.monacoReady&&await window.monacoReady;if(monaco){state.monaco=monaco;state.editor=monaco.editor.create(els.monaco,{value:'',language:'html',theme:document.body.classList.contains('light')?'vs':'vs-dark',automaticLayout:true,minimap:{enabled:false},fontSize:13});state.editor.onDidChangeModelContent(function(){if(state.activeFile){setText(state.activeFile,state.editor.getValue());els.saveState.textContent='Saved locally';updatePreviewDebounced()}});return}}catch(e){}els.monaco.hidden=true;els.fallback.hidden=false;els.fallback.oninput=function(){if(state.activeFile){setText(state.activeFile,els.fallback.value);els.saveState.textContent='Saved locally';updatePreviewDebounced()}}}
function selectFile(n){state.activeFile=n;els.activeFile.textContent=n;$$('.file-item').forEach(function(b){b.classList.toggle('active',b.dataset.file===n)});if(state.editor){state.editor.setValue(textFile(n)?getText(n):'');state.editor.setModelLanguage(state.editor.getModel(),lang(n))}else els.fallback.value=textFile(n)?getText(n):'';updatePreview()}
function renderFiles(){els.fileList.innerHTML='';var ns=Array.from(state.files.keys()).sort();els.fileCount.textContent=ns.length+' files';ns.forEach(function(n){var b=document.createElement('button');b.className='file-item';b.type='button';b.dataset.file=n;b.innerHTML='<span>'+fileIcon(n)+'</span><span>'+esc(n)+'</span>';b.onclick=function(){selectFile(n)};els.fileList.appendChild(b)})}
async function assetMap(){var map={};state.files.forEach(function(bytes,n){if(/\.(png|jpe?g|gif|webp|svg|ico)$/i.test(n)){var mime=/\.png$/i.test(n)?'image/png':/\.jpe?g$/i.test(n)?'image/jpeg':/\.gif$/i.test(n)?'image/gif':/\.webp$/i.test(n)?'image/webp':/\.svg$/i.test(n)?'image/svg+xml':'image/x-icon';var bin='';for(var i=0;i<bytes.length;i++)bin+=String.fromCharCode(bytes[i]);map[n]='data:'+mime+';base64,'+btoa(bin)}});return map}
function rewriteCss(css,assets){return css.replace(/url\((['"]?)([^'")]+)\1\)/gi,function(m,q,u){var p=normalizePath(u);return assets[p]?'url("'+assets[p]+'")':m})}
var previewTimer=null;function updatePreviewDebounced(){clearTimeout(previewTimer);previewTimer=setTimeout(updatePreview,260)}
async function updatePreview(){if(!state.current)return;var html=state.files.has('index.html')?getText('index.html'):'';var css=state.files.has('styles.css')?getText('styles.css'):state.files.has('style.css')?getText('style.css'):'';var js=state.files.has('app.js')?getText('app.js'):'';var assets=await assetMap();css=rewriteCss(css,assets);Object.keys(assets).forEach(function(n){var base=n.split('/').pop();['src','href'].forEach(function(attr){html=html.replaceAll(attr+'="'+n+'"',attr+'="'+assets[n]+'"').replaceAll(attr+"='"+n+"'",attr+"='"+assets[n]+"'").replaceAll(attr+'="'+base+'"',attr+'="'+assets[n]+'"').replaceAll(attr+"='"+base+"'",attr+"='"+assets[n]+"'")})});var doc='<!doctype html><html><head><meta charset="utf-8"><style>'+css+'</style></head><body>'+html+'<script>'+js.replace(/<\/script/gi,'<\\/script')+'<\/script></body></html>';els.preview.srcdoc=doc}
function loadDone(){try{state.done=JSON.parse(safeGet('oml-done-'+state.current.meta.id)||'{}')}catch(e){state.done={}}}function saveDone(){safeSet('oml-done-'+state.current.meta.id,JSON.stringify(state.done))}
function escapeRe(v){return String(v).replace(/[|\\{}()[\]^$+*?.-]/g,'\\$&')}
function evalCheck(c){var name=normalizePath(c.file||state.activeFile||''),txt=state.files.has(name)?getText(name):'';try{if(c.type==='contains')return c.flags&&c.flags.indexOf('i')>=0?txt.toLowerCase().indexOf(String(c.value).toLowerCase())>=0:txt.indexOf(String(c.value))>=0;if(c.type==='not_contains')return txt.indexOf(String(c.value))<0;if(c.type==='min_length')return txt.length>=Number(c.value||0);if(c.type==='regex')return new RegExp(c.pattern,c.flags||'').test(txt);if(c.type==='files_exist')return (c.files||[]).every(function(f){return state.files.has(normalizePath(f))});if(c.type==='html_elements'){var d=new DOMParser().parseFromString(txt,'text/html');return d.querySelectorAll(c.tag).length>=Number(c.min||1)}if(c.type==='css_property')return new RegExp('[-a-z]+\\s*:\\s*'+escapeRe(c.value||''),'i').test(txt);if(c.all)return c.all.every(evalCheck);if(c.any)return c.any.some(evalCheck);return false}catch(e){return false}}
function taskItems(){return (state.current.meta.homework&&state.current.meta.homework.tasks)||[]}function renderTasks(){var ts=taskItems();els.tasks.innerHTML=ts.length?ts.map(function(t,i){return '<label class="task '+(state.done[i]?'done':'')+'"><input type="checkbox" data-task="'+i+'" '+(state.done[i]?'checked':'')+'><div><strong>'+esc(t.title)+'</strong><p>'+esc(t.description||'')+'</p></div><button class="tiny" data-check="'+i+'" type="button">Check</button></label>'}).join(''):'<div class="hints">No homework was configured for this class.</div>';$$('[data-task]').forEach(function(c){c.onchange=function(){state.done[c.dataset.task]=c.checked;saveDone();renderTasks()}});$$('[data-check]').forEach(function(b){b.onclick=function(){checkTask(Number(b.dataset.check))}})}
function checkTask(i){var t=taskItems()[i],checks=t&&t.checks||[],ok=checks.length?checks.every(evalCheck):true;if(ok){state.done[i]=true;saveDone();renderTasks();toast('Task complete ✓')}else toast('Not complete yet')}
$('#checkAll').onclick=function(){taskItems().forEach(function(t,i){if((t.checks||[]).every(evalCheck))state.done[i]=true});saveDone();renderTasks();toast('Homework checked')};
function renderHints(){var h=(state.current.meta.homework&&state.current.meta.homework.hints)||[];els.hints.innerHTML=h.length?h.map(function(x,i){return '<div class="hint" '+(i===0?'':'hidden')+'>'+esc(x)+'</div>'}).join(''):'No hints configured.';state.hint=0}
$('#nextHint').onclick=function(){var a=els.hints.querySelectorAll('.hint');if(!a.length)return;state.hint=(state.hint+1)%a.length;a.forEach(function(x,i){x.hidden=i!==state.hint})};

async function openClass(id){var meta=(state.catalog.classes||[]).find(function(x){return x.id===decodeURIComponent(id)});if(!meta)return toast('Class not found');if(!(await ensureZip()))return toast('ZIP engine unavailable');try{var env=await fetch(meta.resource).then(function(r){return r.json()}),bytes=await decryptEnv(env,state.password),zip=await JSZip.loadAsync(bytes);state.files=new Map();for(var key in zip.files){if(zip.files[key].dir)continue;var n=normalizePath(key);if(!n||n.indexOf('.git/')===0||n.indexOf('node_modules/')>=0)continue;state.files.set(n,await zip.files[key].async('uint8array'))}state.original=bytes;state.current={meta:meta};loadDone();view('workspace');renderFiles();els.wsTitle.textContent=meta.title;els.wsDescription.textContent=meta.description||'';els.original.disabled=false;els.edited.disabled=false;var first=state.files.has('index.html')?'index.html':Array.from(state.files.keys()).find(function(n){return /\.(html?|css)$/i.test(n)})||Array.from(state.files.keys())[0];await setupEditor();if(first)selectFile(first);renderTasks();renderHints()}catch(e){console.error(e);toast('Could not open this class')}}
function markdown(md){var s=String(md||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');s=s.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\x60([^\x60]+)\x60/g,'<code>$1</code>');return s.split(/\n\n+/).map(function(x){return /^<h[123]>/.test(x)?x:'<p>'+x.replace(/\n/g,'<br>')+'</p>'}).join('')}
async function openBlog(id){var meta=(state.catalog.blogs||[]).find(function(x){return x.id===decodeURIComponent(id)});if(!meta)return toast('Article not found');if(!(await ensureZip()))return toast('ZIP engine unavailable');try{var env=await fetch(meta.resource).then(function(r){return r.json()}),bytes=await decryptEnv(env,state.password),zip=await JSZip.loadAsync(bytes),name=Object.keys(zip.files).find(function(n){return /(^|\/)(article|index|readme)\.md$/i.test(n)})||Object.keys(zip.files).find(function(n){return /\.md$/i.test(n)});var md=name?await zip.files[name].async('text'):meta.description||'';$('#articleContent').innerHTML=markdown(md);view('article')}catch(e){toast('Could not open article')}}
async function downloadZip(edited){if(!state.current||!(await ensureZip()))return;var zip=new JSZip();state.files.forEach(function(bytes,n){if(edited&&textFile(n))bytes=new TextEncoder().encode(getText(n));zip.file(n,bytes)});var blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=state.current.meta.id+'-'+(edited?'edited':'provided')+'.zip';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},2000)}
els.original.onclick=function(){downloadZip(false)};els.edited.onclick=function(){downloadZip(true)};$('#refreshPreview').onclick=updatePreview;$('#popout').onclick=function(){var w=window.open();if(w){w.document.write(els.preview.srcdoc);w.document.close()}};$('#formatBtn').onclick=function(){if(!state.editor)return;var v=state.editor.getValue();if(/^\s*</.test(v))v=v.replace(/>\s*</g,'>\n<');state.editor.setValue(v);toast('Basic formatting applied')};
async function boot(){document.getElementById('year').textContent=new Date().getFullYear();await siteInfo();var remembered=safeGet('oml-session');if(remembered)await unlock(remembered);else route()}boot();
})();