const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const store={get(k,f){try{return JSON.parse(localStorage.getItem("owl_"+k))??f}catch{return f}},set(k,v){localStorage.setItem("owl_"+k,JSON.stringify(v))}};
const toast=(m)=>{const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)};
const sections={overview:"Overview","web-lab":"Web Lab","analytics":"Analytics","marketing":"Marketing","study":"Study Hub","projects":"Projects","notes":"Notes","tasks":"Tasks","resources":"Resources"};
function go(id){$$(".page-section").forEach(x=>x.classList.toggle("active",x.id===id));$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.section===id));$("#breadcrumb").textContent=sections[id]||"Overview";history.replaceState(null,"","#"+id);window.scrollTo({top:0,behavior:"smooth"});if(innerWidth<760)closeNav()}
function closeNav(){$("#sidebar").classList.remove("open");$("#sidebarOverlay").classList.remove("show")}
$$(".nav-item").forEach(b=>b.onclick=()=>go(b.dataset.section));$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
$("#openSidebar").onclick=()=>{$("#sidebar").classList.add("open");$("#sidebarOverlay").classList.add("show")};$("#closeSidebar").onclick=closeNav;$("#sidebarOverlay").onclick=closeNav;
const savedTheme=store.get("theme","dark");if(savedTheme==="light")document.body.classList.add("light");
function toggleTheme(){document.body.classList.toggle("light");store.set("theme",document.body.classList.contains("light")?"light":"dark");toast("Theme updated")}
$("#themeBtn").onclick=toggleTheme;$("#settingsTheme").onclick=toggleTheme;
$("#settingsBtn").onclick=()=>$("#settingsModal").showModal();$("#profileBtn").onclick=()=>$("#profileModal").showModal();
$$("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close).close());
setInterval(()=>{const d=new Date();$("#liveClock").textContent=d.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});$("#liveDate").textContent=d.toLocaleDateString([], {weekday:"short",month:"short",day:"numeric"})},1000);

const defaults={html:'<main class="card">\n  <span>OB / WEB LAB</span>\n  <h1>Build something.</h1>\n  <p>Edit the files and press Run preview.</p>\n  <button onclick="hello()">Test JavaScript</button>\n</main>',css:'body{margin:0;min-height:100vh;display:grid;place-items:center;background:#0b1220;color:#f4f7fb;font:16px system-ui}.card{width:min(520px,80vw);padding:38px;border:1px solid #33425c;border-radius:24px;background:#111b2b;box-shadow:0 25px 70px #0005}.card span{font-size:10px;letter-spacing:.2em;color:#8dbbff}.card h1{font-size:42px;letter-spacing:-.04em;margin:12px 0}.card p{color:#94a2b7}.card button{padding:10px 14px;border:0;border-radius:10px;background:#eef4ff;color:#0b1220;font-weight:700}',js:'function hello(){alert("JavaScript is running inside Obaid Web Lab.");}'};
["html","css","js"].forEach(k=>$("#"+k+"Editor").value=store.get("lab_"+k,defaults[k]));
function runLab(){const h=$("#htmlEditor").value,c=$("#cssEditor").value,j=$("#jsEditor").value;$("#previewFrame").srcdoc=h+"<style>"+c+"</style><script>"+j.replaceAll("</script>","<\\/script>")+"<\\/script>";store.set("lab_html",h);store.set("lab_css",c);store.set("lab_js",j);let n=store.get("labRuns",0)+1;store.set("labRuns",n);$("#labMetric").textContent=n;toast("Preview updated")}
$$(".editor-tab").forEach(b=>b.onclick=()=>{$$(".editor-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".code-editor").forEach(x=>x.classList.add("hidden"));$("#"+b.dataset.editor+"Editor").classList.remove("hidden")});
$$(".code-editor").forEach(e=>e.addEventListener("input",()=>store.set("lab_"+e.id.replace("Editor",""),e.value)));
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter"){e.preventDefault();if($("#web-lab").classList.contains("active"))runLab()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openCommands()}});
$("#runLabBtn").onclick=runLab;$("#openPreview").onclick=()=>window.open($("#previewFrame").srcdoc?"about:blank":"about:blank","_blank");$("#resetLab").onclick=()=>{["html","css","js"].forEach(k=>$("#"+k+"Editor").value=defaults[k]);runLab();toast("Lab reset")};runLab();$("#labMetric").textContent=store.get("labRuns",0);

let tasks=store.get("tasks",[{text:"Finish Web Lab landing experience",bucket:"Web",done:false},{text:"Review one analytics concept",bucket:"Data",done:false},{text:"Plan one useful content idea",bucket:"Marketing",done:false}]);
function renderTasks(){const list=$("#taskList");list.innerHTML="";tasks.forEach((t,i)=>{const row=document.createElement("div");row.className="task-row "+(t.done?"done":"");row.innerHTML='<input type="checkbox" '+(t.done?"checked":"")+'><label></label><small>'+t.bucket+'</small><button class="text-btn">×</button>';row.querySelector("label").textContent=t.text;row.querySelector("input").onchange=()=>{t.done=!t.done;saveTasks()};row.querySelector("button").onclick=()=>{tasks.splice(i,1);saveTasks()};list.append(row)});$("#taskMetric").textContent=tasks.filter(x=>x.done).length}
function saveTasks(){store.set("tasks",tasks);renderTasks();renderFocus();toast("Tasks updated")}
$("#taskForm").onsubmit=e=>{e.preventDefault();tasks.unshift({text:$("#taskInput").value.trim(),bucket:$("#taskBucket").value,done:false});$("#taskInput").value="";saveTasks()};$("#clearDone").onclick=()=>{tasks=tasks.filter(x=>!x.done);saveTasks()};function renderFocus(){const f=$("#focusList");if(!f)return;f.innerHTML=tasks.slice(0,4).map((t,i)=>'<label class="focus-item"><input type="checkbox" data-focus="'+i+'" '+(t.done?"checked":"")+"><span>'+t.text+'</span><small>'+t.bucket+'</small></label>').join("");$$("[data-focus]").forEach(x=>x.onchange=()=>{tasks[+x.dataset.focus].done=x.checked;saveTasks()})}renderTasks();renderFocus();

let notes=store.get("notes",[]);function renderNotes(){$("#noteList").innerHTML=notes.length?notes.slice().reverse().map(n=>'<div class="note-item"><strong></strong><small>'+new Date(n.date).toLocaleString()+'</small></div>').join(""):'<div class="note-item"><small>No saved notes yet.</small></div>';notes.slice().reverse().forEach((n,i)=>$("#noteList").children[i]?.querySelector("strong")&&( $("#noteList").children[i].querySelector("strong").textContent=n.text.slice(0,100)))}renderNotes();$("#saveNote").onclick=()=>{const text=$("#noteEditor").value.trim();if(!text)return toast("Write something first");notes.push({text,date:Date.now()});store.set("notes",notes);$("#noteEditor").value="";renderNotes();toast("Note saved locally")};

let timer=1500,timerOn=false,timerId;function timerPaint(){let m=Math.floor(timer/60),s=timer%60;$("#timerDisplay").textContent=String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")}function timerToggle(){timerOn=!timerOn;$("#timerToggle").textContent=timerOn?"Pause":"Start";if(timerOn){timerId=setInterval(()=>{timer--;timerPaint();if(timer<=0){clearInterval(timerId);timerOn=false;$("#timerToggle").textContent="Start";toast("Focus block complete")}},1000)}}$("#timerToggle").onclick=timerToggle;$("#startFocus").onclick=()=>{go("study");if(!timerOn)timerToggle()};$("#timerReset").onclick=()=>{clearInterval(timerId);timerOn=false;timer=1500;$("#timerToggle").textContent="Start";timerPaint()};

function openCommands(){const m=$("#commandModal");m.showModal();$("#commandInput").focus();renderCommands("")}const commandData=Object.entries(sections);function renderCommands(q){$("#commandResults").innerHTML=commandData.filter(([id,n])=>n.toLowerCase().includes(q.toLowerCase())).map(([id,n])=>'<button class="command-result" data-command="'+id+'">'+n+'</button>').join("");$$("[data-command]").forEach(b=>b.onclick=()=>{$("#commandModal").close();go(b.dataset.command)})}$("#commandBtn").onclick=openCommands;$("#commandInput").oninput=e=>renderCommands(e.target.value);
$("#newAnalysis").onclick=()=>{go("notes");$("#noteEditor").value="Analysis question:\n\nEvidence:\n\nInsight:\n\nAction:\n";toast("Analysis template opened")};$("#addCampaign").onclick=()=>{go("tasks");$("#taskInput").value="Draft next marketing campaign idea";$("#taskInput").focus()};$("#addProject").onclick=()=>{go("notes");$("#noteEditor").value="Project brief:\n\nGoal:\n\nUser:\n\nNext milestone:\n\n";toast("Project brief opened")};
$("#resetLocal").onclick=()=>{if(confirm("Reset all local Obaid Web Lab data?")){Object.keys(localStorage).filter(k=>k.startsWith("owl_")).forEach(k=>localStorage.removeItem(k));location.reload()}};
const hash=location.hash.slice(1);if(sections[hash])go(hash);
$$("[data-savecheck]").forEach(x=>{x.checked=store.get("check_"+x.dataset.savecheck,false);x.onchange=()=>store.set("check_"+x.dataset.savecheck,x.checked)});
