import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import os from 'node:os';import {execFileSync} from 'node:child_process';
const ROOT=process.cwd(),DIST=path.join(ROOT,'dist'),WORK=path.join(os.tmpdir(),'oml-build-'+crypto.randomUUID());const PASSWORD=process.env.CLASS_ACCESS_PASSWORD;const BUILD_PASSWORD=PASSWORD||(process.env.GITHUB_ACTIONS?'':'demo-only-change-me');if(!BUILD_PASSWORD)throw new Error('CLASS_ACCESS_PASSWORD is required in GitHub Actions.');const ITERATIONS=180000;
function mkdir(p){fs.mkdirSync(p,{recursive:true})}function clean(p){if(fs.existsSync(p))fs.rmSync(p,{recursive:true,force:true});mkdir(p)}function safeId(s){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)||'item'}function copy(a,b){mkdir(path.dirname(b));fs.cpSync(a,b,{recursive:true})}
function firstPara(f){if(!f||!fs.existsSync(f))return '';const t=fs.readFileSync(f,'utf8').replace(/^#.*$/gm,'').trim();return (t.split(/\n\s*\n/)[0]||'').replace(/[*_]/g,'').slice(0,300)}
function inferTags(name,dir){const src=(name+' '+path.basename(dir)+' '+fs.readdirSync(dir).join(' ')).toLowerCase();const map=[['html','HTML'],['css','CSS'],['form','Forms'],['flex','Flexbox'],['grid','CSS Grid'],['responsive','Responsive'],['javascript','JavaScript'],['js','JavaScript'],['dom','DOM'],['semantic','Semantics'],['access','Accessibility'],['layout','Layout'],['animation','Animation'],['git','Git'],['github','GitHub'],['portfolio','Portfolio'],['project','Project']];return [...new Set(map.filter(x=>src.includes(x[0])).map(x=>x[1]))]}
function titleFromName(s){return String(s).replace(/\.zip$/i,'').replace(/^\d+[-_ ]*/,'').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase()).trim()||'Untitled'}
function parseMeta(dir,type,name){let meta={};for(const f of ['metadata.json','meta.json']){const p=path.join(dir,f);if(fs.existsSync(p)){try{meta=JSON.parse(fs.readFileSync(p,'utf8'));break}catch{}}}const readme=['README.md','readme.md','article.md','index.md'].map(f=>path.join(dir,f)).find(fs.existsSync);const idx=path.join(dir,'index.html');let title=meta.title||'',description=meta.description||meta.summary||'';if(!title&&readme){const h=fs.readFileSync(readme,'utf8').match(/^#\s+(.+)$/m);if(h)title=h[1].trim()}if(!title&&fs.existsSync(idx)){const h=fs.readFileSync(idx,'utf8').match(/<title[^>]*>([\s\S]*?)<\/title>/i)||fs.readFileSync(idx,'utf8').match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);if(h)title=h[1].replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim()}if(!title)title=titleFromName(name);if(!description)description=firstPara(readme)||'A practical web development lesson.';const tags=[...(Array.isArray(meta.tags)?meta.tags:[]),...inferTags(name,dir)];const unique=[...new Set(tags)];const defaults=type==='class'?{level:'Beginner',duration:'Self-paced',tags:unique.length?unique:['HTML','CSS'],order:999,featured:false,homework:{hints:['Read the task carefully.','Change one thing at a time and use the live preview.'],tasks:[]}}:{level:'General',duration:'5 min read',tags:unique.length?unique:['Web design'],order:999,featured:false};const merged={...defaults,...meta,title,description,summary:meta.summary||description,tags:unique.length?unique:defaults.tags};if(type==='class'){const ts=Array.isArray(merged.homework?.tasks)?merged.homework.tasks:[];merged.homework={...(defaults.homework||{}),...(merged.homework||{}),tasks:ts.map((t,i)=>typeof t==='string'?{title:t,description:'Complete this learning task.',checks:[]}:{title:t.title||('Task '+(i+1)),description:t.description||'',checks:Array.isArray(t.checks)?t.checks:[]})}}return {...merged,id:safeId(meta.id||name),type}}
function findSource(input,tmp){if(fs.statSync(input).isDirectory())return input;mkdir(tmp);execFileSync('unzip',['-q',input,'-d',tmp]);const e=fs.readdirSync(tmp,{withFileTypes:true}).filter(x=>!x.name.startsWith('.'));if(e.length===1&&e[0].isDirectory())return path.join(tmp,e[0].name);return tmp}
function encrypt(buf,password,aad){const salt=crypto.randomBytes(16),iv=crypto.randomBytes(12),key=crypto.pbkdf2Sync(Buffer.from(password),salt,ITERATIONS,32,'sha256'),c=crypto.createCipheriv('aes-256-gcm',key,iv);c.setAAD(Buffer.from(aad));const data=Buffer.concat([c.update(buf),c.final()]);return {version:1,algorithm:'AES-256-GCM',kdf:'PBKDF2-SHA256',iterations:ITERATIONS,salt:salt.toString('base64'),iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64'),aad,data:data.toString('base64')}}
function zipDir(dir){const out=path.join(WORK,crypto.randomUUID()+'.zip');const cwd=process.cwd();process.chdir(dir);try{execFileSync('zip',['-qr',out,'.','-x','*.DS_Store','.git/*','node_modules/*'])}finally{process.chdir(cwd)}return fs.readFileSync(out)}
function processCollection(folder,type,catalog){const base=path.join(ROOT,folder);if(!fs.existsSync(base))return;const outDir=path.join(DIST,'data',type==='class'?'classes':'blogs');mkdir(outDir);fs.readdirSync(base,{withFileTypes:true}).filter(e=>!e.name.startsWith('.')).forEach(ent=>{const tmp=path.join(WORK,'x-'+crypto.randomUUID());const src=findSource(path.join(base,ent.name),tmp);const meta=parseMeta(src,type,ent.name);const resource='./data/'+(type==='class'?'classes':'blogs')+'/'+meta.id+'.enc.json';fs.writeFileSync(path.join(outDir,meta.id+'.enc.json'),JSON.stringify(encrypt(zipDir(src),BUILD_PASSWORD,type+':'+meta.id+':package:v1')));catalog.push({...meta,resource,updatedAt:new Date().toISOString()})})}
clean(DIST);clean(WORK);['index.html','styles.css','app.js','sw.js','site.webmanifest','robots.txt','404.html','editor.html'].forEach(f=>copy(path.join(ROOT,f),path.join(DIST,f)));copy(path.join(ROOT,'assets'),path.join(DIST,'assets'));
const cfg=JSON.parse(fs.readFileSync(path.join(ROOT,'site-config.json'),'utf8'));const catalog={site:cfg,classes:[],blogs:[],generatedAt:new Date().toISOString()};processCollection('Classes','class',catalog.classes);processCollection('Blogs','blog',catalog.blogs);catalog.classes.sort((a,b)=>(Number(a.order)||999)-(Number(b.order)||999)||a.title.localeCompare(b.title));catalog.blogs.sort((a,b)=>(Number(a.order)||999)-(Number(b.order)||999)||a.title.localeCompare(b.title));
mkdir(path.join(DIST,'data/classes'));mkdir(path.join(DIST,'data/blogs'));fs.writeFileSync(path.join(DIST,'data/catalog.enc.json'),JSON.stringify(encrypt(Buffer.from(JSON.stringify(catalog)),BUILD_PASSWORD,'catalog:v1')));fs.writeFileSync(path.join(DIST,'data/site.json'),JSON.stringify(cfg,null,2));fs.writeFileSync(path.join(DIST,'data/build-info.json'),JSON.stringify({version:1,generatedAt:catalog.generatedAt,classes:catalog.classes.length,blogs:catalog.blogs.length,commit:process.env.GITHUB_SHA||null},null,2));
const siteUrl=(process.env.SITE_URL||'https://example.github.io/mentor-lab').replace(/\/$/,'');const urls=[siteUrl,...catalog.classes.map(x=>siteUrl+'/?class='+encodeURIComponent(x.id)),...catalog.blogs.map(x=>siteUrl+'/?blog='+encodeURIComponent(x.id))];fs.writeFileSync(path.join(DIST,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(u=>'  <url><loc>'+u+'</loc></url>').join('\n')+'\n</urlset>');fs.writeFileSync(path.join(DIST,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: '+siteUrl+'/sitemap.xml\n');fs.writeFileSync(path.join(DIST,'.nojekyll'),'');fs.rmSync(WORK,{recursive:true,force:true});console.log('Built '+catalog.classes.length+' classes and '+catalog.blogs.length+' blogs.')